### ISSUE TITLE
batch call

### ISSUE THREAD

**Issue by thegodone** [snu-micc/LocalMapper#2]
For very large dataset it would be nice to leverage torch speed of large batch.
Can you provide a apply script that can accept more than one case on new dataset similar to test.py or even more interesting a function ?

**Comment by shuan4638** [comment]
Thanks for the good suggestion. It shouldn't be hard to make this funciton.
I will find a time these weeks to update the code and get back to you :)

**Comment by thegodone** [comment]
Great, ultimately I was thinking of a code to apply on a pandas Dataframe.

But anything that can leverage large batch size apply/eval would be great
featuring.

**Comment by shuan4638** [comment]
Just added that function with a little change in the output format.
