### ISSUE TITLE
cannot import dgl?

### ISSUE THREAD

**Issue by suongbatran** [snu-micc/LocalMapper#5]
I install localmapper using pip from README then I'm having this error why trying:

from localmapper import localmapper

ImportError: Cannot load Graphbolt C++ library

Please let me know if I can provide further information. Thank you.

**Comment by shuan4638** [comment]
Although I've tested it in several difference devices, I haven't encounter this issue yet. I think this issue is related to the dgl and cuda version.

Can you see any of the solutions in [this discussion](https://discuss.dgl.ai/t/importerror-cannot-load-graphbolt-c-library/4291/15) works for you?

**Comment by shuan4638** [comment]
I am closing this issue if there's no following discussion on this.
